name = "alaradinc-fyi"
compatibility_date = "2025-11-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = "."

[env.production]
pages_build_output_dir = "code/.vercel/output/static"

